#chapter1.rpy
#chapter 1 (main story)

label chapter1:
    scene bg jones_sarlot_farmhouse
    pause 3
    scene bg farmhouse_night
    show sar shocked at center
    sar "AHHHHHHHHHH!"
    sar "What is Jones doing?"
    show sar sad at center
    sar "He's drunk again..."
    show sar resent at center
    sar "Anyways,"
    show sar neutral at center
    sar "Old Major has called us to meet in the barn to share a dream he had last night."
    sar "That is going to cost us at least an hour of sleep"
    sar "But since it's him, it's worth it."

    scene bg barn_in
    show major neutral at center
    major "Comrades!"
    major "You have heard already about the strange dream that I had last night."
    major "But I will come to the dream later..."
    major "I have something else to say first."
    major "I do not think, comrades, that I shall be with you for many months longer..."
    major "...and before I die, I feel it my duty to pass on to you such wisdom, as I have acquired."
    major "I have had a long life..."
    major "...I have had much time for thought as I lay alone in my stall."
    major "I think I may say that I understand the nature of life on this earth as well as any animal now living."
    major "It is about this that I wish to speak to you!"
    major "Now, comrades, what is the nature of this life of ours?"
    major "Let us face it, our lives are miserable, laborious and short."
    major "We are born, we are given just so much food as will keep the breath in our bodies,"
    major "those of us who are capable of it are forced to work to the last atom of our strength,"
    major "and the very instant that our usefulness has come to an end..."
    major "...we are slaughtered with hideous cruelty!"
    major "No animal in England knows the meaning of happiness, or leisure after he is a year old."
    major "No animal in England is free!"
    major "But is this simply part of the order of Nature?"
    major "Is it because this land of ours is so poor that it cannot afford a decent life to those who dwell upon it?"
    major "No, comrades, a thousand times no!"
    major "The soil of England is fertile, its climate is good and it is capable of affording food in abundance"
    major "This single farm of ours would supported twice our current population and all of us would be living in comfort and dignity!"
    major "So why then, do we continue in this miserable condition?"
    major "Nearly the whole of the produce of OUR labour is stolen from us by human beings!"
    major "The answer to all our problems is summed up in a single word..."
    major "Man."
    major "Man is the only real enemy we have. Remove Man from the scene, and the root cause of hunger and overwork is abolished forever."
    major "Man is the only creature that consumes without producing. He gives no milk, lays no eggs and yet he is lord of all animals." 
    major "Even our miserable lives are not allowed to reach their natural span!"
    major "No animal escapes the cruel knife in the end..."
    major "Is it not crystal clear then, comrades, that all the evils of this life of ours spring from the tyranny of human beings?"
    major "Only get rid of Man, and the produce of our labour would be our own."
    major "Almost overnight, we could become rich and free!"
    major "So, what must we do you may ask..."
    major "Work night and day, body and soul, for the overthrow of the human race!"
    major "That is my message to you, comrades."
    major "Rebellion!"
    major "I do not know when the rebellion will come."
    major "It might be in a week or in a hundred years, but I know as surely as I see this straw beneath me, that sooner or later justice will be done!"
    major "Fix your eyes on that comrades and above all, pass on this message of mine to those who come after you, so that future generations shall struggle until victorious!"
    major "And remember, your resolution must never falter."
    major "Nothing must lead you astray."
    major "Never listen when they tell you that Man and animals have common interest. It is all lies!"
    major "All men are enemies. All animals are comrades."
    major "Whatever goes upon four legs, or has wings, is a friend."
    major "Don't you forget though that in fighting against Man, we must not come to resemble him."
    major "No animal must ever live in a house, or sleep in a bed, or wear clothes, or drink alcohol, or smoke tobacco, or touch money, or engage in trade."
    major "All the habits of Man are evil."
    major "Above all, no animal must ever tyrannize over his own kind."
    major "No animal must ever kill any other animal."
    major "All animals are equal!"
    major "I believe now is the time to tell you about my dream of last night."
    major "It was a dream of the earth as it will be when Man has vanished."
    major "But it reminded me of something that I had long forgotten..."
    major "Many years ago, when I was a little pig, my mother and the other sows used to sing an old song of which they knew only the tune and the first three words."
    major "I had known the tune in my infancy, but it had long since passed out of my mind."
    major "Last night, however, it came back to me in my dream!"
    major "And what is more, the words of the song also came back - words, I am certain which were sung by the animals of long ago have been lost to memory for generations."
    major "I will sing you that song now, comrades."
    major "I am old and my voice is hoarse, but when I have taught you the tune, you can sing it better for yourselves."
    major "It is called 'Beasts of England'."

    scene bg singing
    "Beasts of England, beasts of Ireland,"
    "Beasts of every land and clime."
    "Hearken to my joyful tidings"
    "Of the golden future time."
    "Soon or late the day is coming,"
    "Tyrant Man shall be overthrown,"
    "And the fruitful fields of England"
    "Shall be trod by beasts alone."
    "Rings shall vanish from our noses,"
    "And the harness from out back,"
    "But and spur shall rush forever,"
    "Cruel whips no more shall crack."
    "Riches more than mind can picture,"
    "Wheat and barley, oats and hay,"
    "Clover, beans and mangel-wurzels"
    "Shall be ours upon that day."
    "Bright will shine the fields of England,"
    "Purer shall its waters be,"
    "Sweeter yer shall blow its breezes"
    "On the day that sets us free."
    "For that day we all must labour,"
    "Though we die before it break;"
    "Cows and horses, geese and turkeys,"
    "All must toil for freedom's sake."
    "Beasts of England, beasts of Ireland,"
    "Beasts of every land and clime,"
    "Hearken well and spread my tidings"
    "Of the golden future time."
    scene bg black_screen
    "BAM!!!!"
    return
#end of chapter1